version: '3'

services:
 
  jenkins-master:
    image: jenkins-consul
    build: .
    networks: 
      - consul-demo
    ports: 
      - "8080:8080"

  jenkins-agent:
    image: jenkins-agent
    build: ../jenkins-agent
    networks:
      - consul-demo
#    ports:
#      - "22:22"
    command: "consul agent -data-dir /tmp/consul -join consul-server-bootstrap -enable-script-checks -config-dir=/tmp/consul.d"
   

  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent


  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2: 
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-3:
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-4:
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  consul-demo:
